@baseUrlDev = http://localhost:3000

###
GET {{baseUrlDev}}/admin HTTP/1.1
Content-Type: application/json

###
GET {{baseUrlDev}}/admin/publish HTTP/1.1
Content-Type: application/json

###
POST {{baseUrlDev}}/admin/key HTTP/1.1
Content-Type: application/json

{
    "key": "qwerty20",
    "expireAt": "2025-01-01T00:00:00.000Z",
    "maxRateAllowedPerMin": 20,
    "isDisabled": false
}

###
GET {{baseUrlDev}}/admin/keys HTTP/1.1
Content-Type: application/json

###

PATCH {{baseUrlDev}}/admin/key HTTP/1.1
Content-Type: application/json

{
    "key": "qwerty18",
    "isDisabled": false
}
